import type {
  Cliente,
  Conversacion,
  EventoAgenda,
  MovimientoFinanciero,
  User,
} from "./types"

/* ----------------------------- USUARIOS MOCK ----------------------------- */
export const MOCK_USERS: User[] = [
  {
    id: "u-1",
    name: "Carla Mendoza",
    email: "superadmin@luzdelsol.com",
    password: "super123",
    role: "super_admin",
    createdAt: "2025-01-12",
    active: true,
  },
  {
    id: "u-2",
    name: "Diego Salazar",
    email: "admin@luzdelsol.com",
    password: "admin123",
    role: "admin",
    createdAt: "2025-02-04",
    active: true,
  },
  {
    id: "u-3",
    name: "Lucía Pérez",
    email: "contador@luzdelsol.com",
    password: "contador123",
    role: "contador",
    createdAt: "2025-03-18",
    active: true,
  },
  {
    id: "u-4",
    name: "Renato Vargas",
    email: "renato.vargas@luzdelsol.com",
    password: "admin123",
    role: "admin",
    createdAt: "2025-05-02",
    active: true,
  },
  {
    id: "u-5",
    name: "María Quispe",
    email: "maria.quispe@luzdelsol.com",
    password: "contador123",
    role: "contador",
    createdAt: "2025-06-10",
    active: false,
  },
]

/* ----------------------------- CLIENTES ----------------------------- */
export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "c-1",
    nombre: "Andrés Fernández",
    email: "andres.f@gmail.com",
    telefono: "+51 987 654 321",
    tipo: "Comprador",
    estado: "Activo",
    asesor: "Diego Salazar",
    createdAt: "2026-04-12",
  },
  {
    id: "c-2",
    nombre: "Patricia Ruiz",
    email: "patricia.r@hotmail.com",
    telefono: "+51 999 112 233",
    tipo: "Vendedor",
    estado: "Prospecto",
    asesor: "Renato Vargas",
    createdAt: "2026-04-20",
  },
  {
    id: "c-3",
    nombre: "Grupo Inversiones SAC",
    email: "contacto@gruposac.pe",
    telefono: "+51 988 776 655",
    tipo: "Inversor",
    estado: "Activo",
    asesor: "Diego Salazar",
    createdAt: "2026-03-05",
  },
  {
    id: "c-4",
    nombre: "Miguel Torres",
    email: "mtorres@outlook.com",
    telefono: "+51 945 322 100",
    tipo: "Inquilino",
    estado: "Cerrado",
    asesor: "Renato Vargas",
    createdAt: "2026-02-18",
  },
  {
    id: "c-5",
    nombre: "Sofía Romero",
    email: "sofia.romero@gmail.com",
    telefono: "+51 922 110 998",
    tipo: "Comprador",
    estado: "Activo",
    asesor: "Diego Salazar",
    createdAt: "2026-04-29",
  },
  {
    id: "c-6",
    nombre: "Constructora Andina",
    email: "ventas@andina.pe",
    telefono: "+51 911 223 344",
    tipo: "Inversor",
    estado: "Prospecto",
    asesor: "Renato Vargas",
    createdAt: "2026-04-30",
  },
]

/* ----------------------------- CONVERSACIONES ----------------------------- */
export const MOCK_CONVERSACIONES: Conversacion[] = [
  {
    id: "conv-1",
    cliente: "Andrés Fernández",
    canal: "WhatsApp",
    ultimoMensaje: "Quería confirmar la visita del sábado a las 11am.",
    fecha: "2026-05-05 14:22",
    noLeidos: 2,
  },
  {
    id: "conv-2",
    cliente: "Patricia Ruiz",
    canal: "Email",
    ultimoMensaje: "Adjunto los documentos solicitados para la tasación.",
    fecha: "2026-05-05 11:08",
    noLeidos: 0,
  },
  {
    id: "conv-3",
    cliente: "Grupo Inversiones SAC",
    canal: "Llamada",
    ultimoMensaje: "Reagendamos la reunión para el martes próximo.",
    fecha: "2026-05-04 17:45",
    noLeidos: 0,
  },
  {
    id: "conv-4",
    cliente: "Sofía Romero",
    canal: "WhatsApp",
    ultimoMensaje: "Perfecto, espero la propuesta por escrito.",
    fecha: "2026-05-04 10:12",
    noLeidos: 1,
  },
  {
    id: "conv-5",
    cliente: "Miguel Torres",
    canal: "Presencial",
    ultimoMensaje: "Visita realizada — interesado en negociar el precio.",
    fecha: "2026-05-03 16:30",
    noLeidos: 0,
  },
]

/* ----------------------------- AGENDA ----------------------------- */
export const MOCK_AGENDA: EventoAgenda[] = [
  {
    id: "ev-1",
    titulo: "Visita Departamento San Isidro",
    cliente: "Andrés Fernández",
    fecha: "2026-05-07",
    hora: "11:00",
    tipo: "Visita",
    estado: "Confirmado",
  },
  {
    id: "ev-2",
    titulo: "Tasación Casa Surco",
    cliente: "Patricia Ruiz",
    fecha: "2026-05-08",
    hora: "09:30",
    tipo: "Reunión",
    estado: "Pendiente",
  },
  {
    id: "ev-3",
    titulo: "Firma de contrato",
    cliente: "Miguel Torres",
    fecha: "2026-05-09",
    hora: "16:00",
    tipo: "Firma",
    estado: "Confirmado",
  },
  {
    id: "ev-4",
    titulo: "Llamada de seguimiento",
    cliente: "Grupo Inversiones SAC",
    fecha: "2026-05-10",
    hora: "10:00",
    tipo: "Llamada",
    estado: "Pendiente",
  },
  {
    id: "ev-5",
    titulo: "Visita Oficinas Miraflores",
    cliente: "Sofía Romero",
    fecha: "2026-05-11",
    hora: "15:30",
    tipo: "Visita",
    estado: "Confirmado",
  },
]

/* ----------------------------- INGRESOS ----------------------------- */
export const MOCK_INGRESOS: MovimientoFinanciero[] = [
  {
    id: "in-1",
    concepto: "Comisión venta Dpto. San Isidro",
    categoria: "Comisión",
    monto: 18500,
    fecha: "2026-05-02",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "FAC-0021",
  },
  {
    id: "in-2",
    concepto: "Adelanto alquiler Surco",
    categoria: "Alquiler",
    monto: 4200,
    fecha: "2026-05-01",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "FAC-0022",
  },
  {
    id: "in-3",
    concepto: "Comisión asesoría Grupo Inversiones",
    categoria: "Asesoría",
    monto: 7800,
    fecha: "2026-04-28",
    metodo: "Cheque",
    estado: "Pendiente",
    referencia: "FAC-0023",
  },
  {
    id: "in-4",
    concepto: "Cierre venta Miraflores",
    categoria: "Comisión",
    monto: 25400,
    fecha: "2026-04-22",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "FAC-0024",
  },
  {
    id: "in-5",
    concepto: "Renovación contrato",
    categoria: "Alquiler",
    monto: 3100,
    fecha: "2026-04-15",
    metodo: "Tarjeta",
    estado: "Pagado",
    referencia: "FAC-0025",
  },
]

/* ----------------------------- EGRESOS ----------------------------- */
export const MOCK_EGRESOS: MovimientoFinanciero[] = [
  {
    id: "eg-1",
    concepto: "Sueldos personal abril",
    categoria: "Planilla",
    monto: 14200,
    fecha: "2026-05-01",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "PL-04",
  },
  {
    id: "eg-2",
    concepto: "Publicidad redes sociales",
    categoria: "Marketing",
    monto: 1800,
    fecha: "2026-04-29",
    metodo: "Tarjeta",
    estado: "Pagado",
    referencia: "MK-12",
  },
  {
    id: "eg-3",
    concepto: "Alquiler oficina",
    categoria: "Operativos",
    monto: 3500,
    fecha: "2026-04-28",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "OP-08",
  },
  {
    id: "eg-4",
    concepto: "Servicios públicos",
    categoria: "Operativos",
    monto: 540,
    fecha: "2026-04-27",
    metodo: "Transferencia",
    estado: "Pagado",
    referencia: "OP-09",
  },
  {
    id: "eg-5",
    concepto: "Software CRM (anual)",
    categoria: "Tecnología",
    monto: 2400,
    fecha: "2026-04-20",
    metodo: "Tarjeta",
    estado: "Pendiente",
    referencia: "TI-03",
  },
]
